name: Build and deploy

on:
  push:
    branches:
      - main
      - dev/*

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up node
        uses: actions/setup-node@v5
        with:
          node-version: '24.12.0'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install
        run: pnpm install --no-frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          HUSKY: 0

      - name: Test
        run: pnpm test

      - name: Knip
        run: pnpm dlx knip --no-exit-code --reporter=markdown >> "$GITHUB_STEP_SUMMARY"

  build:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up node
        uses: actions/setup-node@v5
        with:
          node-version: '24.12.0'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install
        run: pnpm install --no-frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
          HUSKY: 0

      - name: Set up node
        uses: actions/setup-node@v5
        with:
          node-version: '24.12.0'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Build
        run: pnpm build
        env:
#          NEXT_PUBLIC_ASSET_PREFIX: https://cdn.nav.no/paw/arbeidssoekerregisteret
          NEXT_PUBLIC_BASE_PATH: /arbeid/veiviser
          HUSKY: 0

#      - name: Upload static files to NAV CDN
#        uses: nais/deploy/actions/cdn-upload/v2@master
#        with:
#          team: paw
#          source: ./.next/static
#          destination: arbeidssoekerregisteret/_next
#          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
#          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps

      - name: Build storybook-static
        run: pnpm build-storybook

      - name: Run test-storybook
        run: pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "pnpm dlx http-server public/storybook --port 6006 --silent" \
          "pnpm dlx wait-on tcp:127.0.0.1:6006 && pnpm test-storybook"

      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: paw
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy to dev
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: [test, build]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          PRINT_PAYLOAD: true

#  deploy-prod:
#    name: Deploy to prod
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#    needs: [test, build]
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v5
#      - name: Deploy
#        uses: nais/deploy/actions/deploy@v2
#        env:
#          CLUSTER: prod-gcp
#          RESOURCE: .nais/prod-gcp/nais.yaml
#          VAR: image=${{ needs.build.outputs.image }}
#          PRINT_PAYLOAD: true
